spring:
  datasource:
    name: unihotel-db
    url: jdbc:mysql://10.64.8.96:3306/ai?useSSL=false&autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;transformedBitIsBoolean=true
    username: root
    password: 147852369
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20j
    maxWait: 15000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    min-idle: 5
    log-abandoned: true
    remove-abandoned: true
    remove-abandoned-timeout: 1800
    type: com.alibaba.druid.pool.DruidDataSource

  boot:
    admin:
      client:
        prefer-ip: true
      url: http://10.64.8.96:8888/admin

logging:
  level.org.hibernate.SQL: trace
  level.org.hibernate.type: trace


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #配置映射文件位置，classpath指resources
  type-aliases-package: cn.unihotel.entry


pagehelper:
  helperDialect: mysql                           #分页插件方言选择
  reasonable: true                               #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
  supportMethodsArguments: true