spring:
    datasource.url: jdbc:mysql://10.64.8.96:3306/ai?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;transformedBitIsBoolean=true
    datasource.username: root
    datasource.password: 147852369
    jpa.hibernate.ddl-auto: none

    boot:
        admin:
            client:
                prefer-ip: true
            url: http://10.64.8.96:8888/admin