spring:
    datasource.url: jdbc:mysql://10.64.8.129:3306/reminder?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;transformedBitIsBoolean=true
    datasource.username: reminder
    datasource.password: 123456
    jpa.hibernate.ddl-auto: none

    boot:
        admin:
            client:
                prefer-ip: true
            url: http://10.64.8.133:8888/admin

management.security.enabled: false