spring:
    datasource:
        name: ucc-db
        url: jdbc:mysql://10.64.8.166:3306/ucc?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;transformedBitIsBoolean=true
        username: udata
        password: 123456
        driver-class-name: org.mariadb.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 15000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j

    #none, validate, update, create, create-drop
    jpa.hibernate.ddl-auto: update

    boot:
        admin:
            client:
                prefer-ip: true
            url: http://10.64.8.133:8888/admin
logging:
    level.org.hibernate.SQL: trace
    level.org.hibernate.type: trace

management.security.enabled: false

#mybatis  by  wangxiaoyu  2018-08-28
mybatis:
   mapper-locations: classpath:mapper/*Mapper.xml
   type-aliases-package: cn.cucsi.bsd.ucc.data.domain
