spring:
    datasource:
        name: ucc-db
        url: jdbc:p6spy:mysql://10.64.8.166:3306/ucc?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;transformedBitIsBoolean=true
        username: udata
        password: 123456
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 15000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
    interactive_timeout: 28800000 # zss 解决8小时断链
    wait_timeout: 28800000 # zss 解决8小时断链
    #none, validate, update, create, create-drop
    jpa.hibernate.ddl-auto: update

    boot:
        admin:
            client:
                prefer-ip: true
            url: http://10.64.8.133:8888/admin

    redis:
      # redis服务器地址（默认为localhost）
      host: 10.64.8.133
      # redis端口（默认为6379）
      port: 6379
      # redis访问密码（默认为空）
      password:
      # redis连接超时时间（单位为毫秒）
      timeout: 0
      # redis连接池配置
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1
logging:
    level.org.hibernate.SQL: trace
    level.org.hibernate.type: trace

management.security.enabled: false

#mybatis  by  wangxiaoyu  2018-08-28
mybatis:
   mapper-locations: classpath:mapper/*Mapper.xml
   type-aliases-package: cn.cucsi.bsd.ucc.data.domain
   defaultExecutorType: SIMPLE

ucc.zk:
  hostPort: 10.64.8.133:2181
  sessionTimeout: 10000
