spring:
    datasource.url: jdbc:mysql://10.64.8.129:3306/reminder?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;transformedBitIsBoolean=true
    datasource.username: reminder
    datasource.password: 123456
    jpa.hibernate.ddl-auto: none

    boot:
        admin:
            client:
                prefer-ip: true
            url: http://10.64.8.133:8888/admin

    redis:
       # redis服务器地址（默认为localhost）
       host: 10.64.8.133
       # redis端口（默认为6379）
       port: 6379
       # redis访问密码（默认为空）
       password:
       # redis连接超时时间（单位为毫秒）
       timeout: 0
       # redis连接池配置
       pool:
         # 最大可用连接数（默认为8，负数表示无限）
         max-active: 8
         # 最大空闲连接数（默认为8，负数表示无限）
         max-idle: 8
         # 最小空闲连接数（默认为0，该值只有为正数才有作用）
         min-idle: 0
         # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
         max-wait: -1

management.security.enabled: false

ucc.zk:
  hostPort: 10.64.8.133:2181
  sessionTimeout: 10000
